import { NavBar } from "@/components/navBar";
import "@fontsource/montserrat/400.css";
import "@fontsource/montserrat/700.css";
import "./global.css";
import { Footer } from "@/components/Footer";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <NavBar />
        </nav>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
